start:
  - run: |
      ./.backend/start.sh
stop:
  - run: |
      ./.backend/stop.sh

auto_start: false

# env:
#   - TABLE_NAME=example

stdout_log: debug
stderr_log: info

http_proxy:
  prefix: /base/
  port: 8888
  strip_prefix:
